services:
  postgres:
    image: postgres:15-alpine
    container_name: organizations_postgres
    environment:
      POSTGRES_DB: organizations
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5429:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: